segmentation_models_pytorch/base/encoder_decoder.py, segmentation_models_pytorch/fpn/model.py, segmentation_models_pytorch/linknet/model.py, segmentation_models_pytorch/pspnet/model.py, segmentation_models_pytorch/unet/model.py
`None` for models activation (#9)
=> Add `None` activation

segmentation_models_pytorch/base/model.py
Change conv initialization
- distribution: normal -> uniform
- fan_out -> fan_in
- bias -> 0
=> Update decoder initialization

segmentation_models_pytorch/fpn/decoder.py, segmentation_models_pytorch/fpn/model.py
=> Add optional final upsampling

segmentation_models_pytorch/fpn/decoder.py, segmentation_models_pytorch/fpn/model.py, tests/test_models.py
Hi!
See: https://github.com/qubvel/segmentation_models.pytorch/issues/78
=> Add ability to use concatenation instead of addition in FPN

README.md, segmentation_models_pytorch/encoders/__init__.py, segmentation_models_pytorch/encoders/inceptionresnetv2.py, segmentation_models_pytorch/encoders/inceptionv4.py
Hi,
I used your repo to implement some new encoders & decoders during the recent Severstal competition (congrats on gold!). 
I found `inceptionv4` worked very well (Private 0.89149, Public 0.91667 single model). You just have to modify the first couple layers to add padding so they upsample back to the same as the input size.
(my editor trimmed some trailing whitespace in the README, sorry about that)
Let me know what you think.
Cheers,
Karl
=> Add inceptionv4 encoder

docker/Dockerfile.dev, segmentation_models_pytorch/encoders/_base.py, segmentation_models_pytorch/encoders/_utils.py, segmentation_models_pytorch/encoders/densenet.py, segmentation_models_pytorch/encoders/dpn.py, segmentation_models_pytorch/encoders/efficientnet.py, segmentation_models_pytorch/encoders/inceptionresnetv2.py, segmentation_models_pytorch/encoders/inceptionv4.py, segmentation_models_pytorch/encoders/mobilenet.py, segmentation_models_pytorch/encoders/resnet.py, segmentation_models_pytorch/encoders/senet.py, segmentation_models_pytorch/encoders/vgg.py, segmentation_models_pytorch/encoders/xception.py, tests/test_models.py
Add `.make_dilated` method to encoders
=> [Feature] Dilated encoders

README.md, segmentation_models_pytorch/__init__.py, segmentation_models_pytorch/pan/__init__.py, segmentation_models_pytorch/pan/decoder.py, segmentation_models_pytorch/pan/model.py, tests/test_models.py
Implementation of [Pyramid Attention Network for Semantic Segmentation ](https://arxiv.org/abs/1805.10180)
=> [New Architecture] Pyramid Attention Network

segmentation_models_pytorch/utils/functional.py
Added check device in function " _take_channels" in functional.py
=> Added check device to ignore_channels

examples/cars segmentation (camvid).ipynb
'model' is still the pretrained model. It took me while to realize what the reason for a good IoU but bad predicted masks is.
greetings
=> use own trained model (best_model) to predict mask

README.md, requirements.txt, segmentation_models_pytorch/__init__.py, segmentation_models_pytorch/deeplabv3/__init__.py, segmentation_models_pytorch/deeplabv3/decoder.py, segmentation_models_pytorch/deeplabv3/model.py, segmentation_models_pytorch/encoders/__init__.py, segmentation_models_pytorch/encoders/timm_efficientnet.py
Add timm efficientnet encoders
=> Add timm efficientnet encoder

segmentation_models_pytorch/base/modules.py
=> Change dim to self.dim in segmentation_models_pytorch.base.modules.ArgMax

README.md, segmentation_models_pytorch/encoders/resnet.py
Add pretrained models from https://github.com/facebookresearch/semi-supervised-ImageNet1K-models
=> Add pretrained models

requirements.txt, segmentation_models_pytorch/__version__.py
=> Fix pytorch-efficientnet version

segmentation_models_pytorch/base/modules.py, segmentation_models_pytorch/deeplabv3/model.py, segmentation_models_pytorch/encoders/__init__.py, segmentation_models_pytorch/encoders/_base.py, segmentation_models_pytorch/fpn/model.py, segmentation_models_pytorch/linknet/model.py, segmentation_models_pytorch/manet/model.py, segmentation_models_pytorch/pan/model.py, segmentation_models_pytorch/pspnet/model.py, segmentation_models_pytorch/unet/model.py, segmentation_models_pytorch/unetplusplus/decoder.py, segmentation_models_pytorch/unetplusplus/model.py, segmentation_models_pytorch/utils/base.py, segmentation_models_pytorch/utils/losses.py, segmentation_models_pytorch/utils/meter.py, segmentation_models_pytorch/utils/metrics.py
=> Merge Activation classes into one, added tanh

segmentation_models_pytorch/encoders/dpn.py
no offense, but PyCharm was complaining :)
=> fixed typo in DPNEncorder

segmentation_models_pytorch/losses/dice.py
This pull request fixes [ignore_index](https://github.com/qubvel/segmentation_models.pytorch/blob/33dc95082ea76fd83af2a8ebd7a4ecbd549aecfa/segmentation_models_pytorch/losses/dice.py#L21) parameter in DiceLoss.  Which does not effect on loss calculation. Now this parameter works as it is supposed to.
=> make ignore_index in DiceLoss work

segmentation_models_pytorch/losses/__init__.py, segmentation_models_pytorch/losses/_functional.py, segmentation_models_pytorch/losses/dice.py, segmentation_models_pytorch/losses/tversky.py, tests/test_losses.py
TverskyLoss is implemented based on DiceLoss. TverskyLossFocall inherits TverskyLoss.
Added two tests for computing soft_tversky_score and TverskyLoss
=> add implementation of TverskyLoss and TverskyLossFocall

segmentation_models_pytorch/losses/_functional.py
=> Fix to_tensor.

HALLOFFAME.md
Competition hosted by IEEE ICETCI and ISRO - India, for extracting substations from aerial images
=> updated HALLOFFAME.md

segmentation_models_pytorch/base/heads.py, segmentation_models_pytorch/base/modules.py
=> Built in flatten

segmentation_models_pytorch/losses/jaccard.py
JaccardLoss doesn't accept a parameter "ignore_index"
=> Update docstring for the JaccardLoss

HALLOFFAME.md, segmentation_models_pytorch/losses/__init__.py, segmentation_models_pytorch/losses/mcc.py, tests/test_losses.py
This contribution adds [Matthew's correlation coefficient](https://en.wikipedia.org/wiki/Matthews_correlation_coefficient) as a loss function. It's [been shown](https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-019-6413-7) [to work quite well](https://arxiv.org/abs/2010.13454) as a loss in situations with imbalanced data. We've had a fair bit of luck using it.
=> Addition of Matthew's Correlation Coefficient loss function

requirements.txt
Updating version to 0.7.1 as mentioned in #580
=> Modifying efficientnet version requirement

segmentation_models_pytorch/losses/tversky.py
FNs should be False Negatives. Please update it.
=> Correct FNs -> False Negatives

segmentation_models_pytorch/metrics/functional.py
Correct functional.py _compute_metric when reduction == "weighted"
=> Correct functional.py _compute_metric

.github/workflows/tests.yml
This PR runs our unit tests on all supported platforms and Python versions.
=> Test on Linux/macOS/Windows for all supported Python versions

README.md
=> Adding withoutBG API as a sponsor

segmentation_models_pytorch/decoders/dpt/decoder.py
=> Fix cls token slicing for DPT

segmentation_models_pytorch/decoders/deeplabv3/model.py
=> Add missing name attribute to deeplabv3 & deeplabv3plus
