qubvel-org/segmentation_models.pytorch

- docker/Dockerfile.dev
Hi!
Don't know, maybe I don't understand something... But it seems that `mock` should be added to development dependencies in Dockerfile.dev, in opposite case tests fail when running it inside docker image built from Dockerfile.dev.
> Add mock library as dependency in Dockerfile.dev

- segmentation_models_pytorch/base/modules.py
refer from https://arxiv.org/abs/1803.02579
the sSE shuold be 
self.sSE = nn.Sequential(nn.Conv2d(in_channels, 1, 1), nn.Sigmoid())
not
self.sSE = nn.Sequential(nn.Conv2d(in_channels, in_channels, 1), nn.Sigmoid())
> fix SCEModule.sSE

- segmentation_models_pytorch/utils/functional.py
When printing a accuracy, only zero are output.
When I checked it, there was a problem with the data type, so I fixed it.
Accuracy -> [[link]](https://github.com/qubvel/segmentation_models.pytorch/blob/6b79c831fa3d8df17a5c4e207ebf304bbf42c094/segmentation_models_pytorch/utils/functional.py#L80)
Ex.
```
>>> aa = torch.zeros((1, 12))
>>> aa[0][4] = 1
>>> aa
tensor([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]])
>>> bb = torch.zeros((1,12))
>>> bb[0][3]=1
>>> bb
tensor([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])
>>> torch.sum(aa==bb)
tensor(10)
>>> torch.sum(aa==bb) / aa.view(-1).shape[0]
tensor(0)
>>> torch.sum(aa==bb, dtype=aa.dtype) / aa.view(-1).shape[0]
tensor(0.8333)
```
> Fix type of tp in Accuracy class

- README.md
- segmentation_models_pytorch/__init__.py
- segmentation_models_pytorch/unetplusplus/__init__.py
- segmentation_models_pytorch/unetplusplus/decoder.py
- segmentation_models_pytorch/unetplusplus/model.py
- tests/test_models.py
Pytorch version of https://arxiv.org/pdf/1807.10165.pdf
Works with different backbones; Seems to work slightly better than Unet
> add unet++

- README.md
- segmentation_models_pytorch/deeplabv3/model.py
- segmentation_models_pytorch/encoders/__init__.py
- segmentation_models_pytorch/encoders/timm_regnet.py
- segmentation_models_pytorch/encoders/timm_res2net.py
- segmentation_models_pytorch/encoders/timm_resnest.py
- segmentation_models_pytorch/encoders/timm_sknet.py
- segmentation_models_pytorch/pan/model.py
- tests/test_models.py
Integrating some encoders using https://github.com/rwightman/pytorch-image-models
> add regnet, res2net, resnest, sknet encoders

- README.md
- docs/models.rst
- segmentation_models_pytorch/__init__.py
- segmentation_models_pytorch/manet/__init__.py
- segmentation_models_pytorch/manet/decoder.py
- segmentation_models_pytorch/manet/model.py
- tests/test_models.py
Paper: https://ieeexplore.ieee.org/abstract/document/9201310
Seems to work better than Unet, similar to Unet++ but faster
An implementation is similar to the original in the paper, except for encoder part.
> Add MAnet 

- README.md
Patch: DeepLabV3Plus documentation link points to Unet model.
> Readme hyperlink patch

- segmentation_models_pytorch/losses/constants.py
The description of constant 'multilabel' and 'multiclass' in the losses module are mixed up
> Wrong losses constant description

- requirements.txt
- segmentation_models_pytorch/encoders/timm_efficientnet.py
- segmentation_models_pytorch/encoders/timm_sknet.py
Closes issues https://github.com/qubvel/segmentation_models.pytorch/issues/417 https://github.com/qubvel/segmentation_models.pytorch/issues/424 
Closes PR https://github.com/qubvel/segmentation_models.pytorch/pull/418
Hi @qubvel!
I would like to update of `timm` library to make it compatible with the latest torch versions.
All changes in code need to be done to fix test errors. I explain each line to help understand what I did in self-review. 
Please, if you OK with this PR merge it and publish a new (I believe v0.2.0) version of the `segmentation-models-pytorch` package.
> Update timm library to 0.4.12

- segmentation_models_pytorch/encoders/__init__.py
Thanks to all contributors for building wonderful project.
Timm universal feature is a great feature and am using it joyfully. However, I found small bug in here 
https://github.com/qubvel/segmentation_models.pytorch/blob/master/segmentation_models_pytorch/encoders/__init__.py#L49
This line makes encoder name starts with "tu-tf.." to "f.."
```
>>> a = "tu-tf_"
>>> a.lstrip("tu-")
'f_'
```
Since lstrip is working with combination of charactors according to the [documentation](https://docs.python.org/3/library/stdtypes.html#str.lstrip), the lstrip function for replacing `tu-` prefix is giving unexpected behavior. So, I made a small fix for it.
Not sure you accept this small PR contribution, but would be happy if it is fixed.
> Fix timm universal prefix replacement

- segmentation_models_pytorch/losses/lovasz.py
In original [LovaszSoftmax repo](https://github.com/bermanmaxim/LovaszSoftmax/blob/7d48792d35a04d3167de488dd00daabbccd8334b/pytorch/lovasz_losses.py#L211):
```python
probas = probas.permute(0, 2, 3, 1).contiguous().view(-1, C)  # B * H * W, C = P, C
```
So, this code in repo:
https://github.com/qubvel/segmentation_models.pytorch/blob/ec807040a580b6c5cb01240bf1fd275100c1858d/segmentation_models_pytorch/losses/lovasz.py#L151
should be changed to:
```python
probas = torch.movedim(probas, 1, -1)
```
> fix bug in lovasz loss

- segmentation_models_pytorch/metrics/functional.py
Two bugs are fixed in this pr.
- `get_stats` under multiclass mode. `matched = target_i * (output_i == target_i)` Wrong predictions will be treated as a matched prediction for class 0.
- `_accuracy`. Only true-positive is counted, true-negative should also be included.
One more question. Two kinds of APIs are provided for metric calculation, the one under utils and the one under metrics, which one is more preferable?
> Fix the wrong stat and accuracy calculation

- .gitignore
- segmentation_models_pytorch/metrics/functional.py
> Fix ignore_index for multiclass metric computation

- segmentation_models_pytorch/losses/tversky.py
I think you should rethink the description of the [Tversky loss function](https://smp.readthedocs.io/en/latest/losses.html#:~:text=Tversky%20loss%20for%20image%20segmentation%20task.%20Where%20TP%20and%20FP%20is%20weighted%20by%20alpha%20and%20beta%20params.%20With%20alpha%20%3D%3D%20beta%20%3D%3D%200.5%2C%20this%20loss%20becomes%20equal%20DiceLoss.%20It%20supports%20binary%2C%20multiclass%20and%20multilabel%20cases).
You can check the article and see that FN and FP are alpha and beta weighted, while your description says that the loss function weights TP and FP. But the function itself is implemented correctly.
> Update the description of TverskyLoss

- segmentation_models_pytorch/metrics/functional.py
The previous return type of `Tuple[torch.LongTensor]` implies that the tuple includes one item. This commit changes this to a tuple of four LongTensors to represent TP, FP, FN, and TN.
> fix return type of get_stats

- .github/workflows/tests.yml
- .pre-commit-config.yaml
- Makefile
- README.md
- setup.py
Calling pre-commit, which is defined already, instead of `flake8` and `black` separately
Also, I would highly recommend installing [pre-commit bot](https://github.com/marketplace/pre-commit-ci), which would also update a PR with fixable on the fly within PR
cc: @qubvel
> use precommit for code linting

- examples/save_load_model_and_share_with_hf_hub.ipynb
- requirements.txt
- segmentation_models_pytorch/__init__.py
- segmentation_models_pytorch/base/hub_mixin.py
- add an example notebook
- update to latest version (fix bug with loading local folder)
> Update HF mixin

- docs/save_load.rst
- examples/save_load_model_and_share_with_hf_hub.ipynb
> Example on how to save and load model along with Albumentations preprocessing

- segmentation_models_pytorch/losses/_functional.py
The Jaccard, Dice and Tversky losses in `losses._functional` are modified based on [JDTLoss](https://github.com/zifuwanggg/JDTLosses/blob/master/losses/jdt_loss.py).
* Since Jaccard and Dice losses are special cases of the Tversky loss [1], the implementation is simplified by calling `soft_tversky_score` when calculating both `jaccard_score` and `dice_score`.
* The original loss functions are incompatible with soft labels. For example, with a ground truth value of 0.5 for a single pixel, the Dice loss is minimized when the predicted value is 1, which is clearly erroneous. To address this, the intersection term is rewritten as $\frac{\|x\|_1 + \|y\|_1 - \|x-y\|_1}{2}$. This reformulation has been proven to retain equivalence with the original versions when the ground truth is binary (i.e. …
> Modify Jaccard, Dice and Tversky losses

- README.md
- docs/models.rst
- segmentation_models_pytorch/__init__.py
- segmentation_models_pytorch/decoders/upernet/__init__.py
- segmentation_models_pytorch/decoders/upernet/decoder.py
- segmentation_models_pytorch/decoders/upernet/model.py
- tests/test_models.py
I tried to add UperNet before. This may not be the best version. Maybe you can have a look.
@GrantorShadow @jawi289o
#906 
- [official repo](https://github.com/CSAILVision/unifiedparsing/blob/master/models/models.py)
- [mmseg repo](https://github.com/open-mmlab/mmsegmentation/blob/v0.17.0/mmseg/models/decode_heads/uper_head.py#L13)
> [feat] Adding UPerNet

- segmentation_models_pytorch/decoders/upernet/decoder.py
> Fix UPerNet decoder typo

- segmentation_models_pytorch/metrics/functional.py
> Fix Metric typo

- segmentation_models_pytorch/decoders/deeplabv3/model.py
- segmentation_models_pytorch/decoders/fpn/model.py
- segmentation_models_pytorch/decoders/linknet/model.py
- segmentation_models_pytorch/decoders/manet/model.py
- segmentation_models_pytorch/decoders/pan/model.py
- segmentation_models_pytorch/decoders/pspnet/model.py
- segmentation_models_pytorch/decoders/unet/model.py
- segmentation_models_pytorch/decoders/unetplusplus/model.py
- segmentation_models_pytorch/decoders/upernet/model.py
- segmentation_models_pytorch/encoders/timm_universal.py
> Expose timm constructor arguments

- examples/camvid_segmentation_multiclass.ipynb
- examples/cars segmentation (camvid).ipynb
The colab links were broken for 2 example notebooks :
- `examples/cars segmentation (camvid).ipynb` : The closing parenthesis indicated the end of the link, so I URL encoded them
- `examples/camvid_segmentation_multiclass.ipynb` : It had the link of the previous notebook
> fix(examples): correct Colab links

- segmentation_models_pytorch/decoders/deeplabv3/decoder.py
- segmentation_models_pytorch/decoders/deeplabv3/model.py
Hi, @qubvel. Thanks for your great work!
This PR fixes #377 and is used to be PR #561, which staled and closed before.
I ran into the issue #377 again to find that the PR can still be effective.
(My typical use case involves processing small images in real time, and a small encoder depth is preferred.)
So, I made some maintenance and rebased on edadc0d.
1. Fix the feature index mismatch which occurs when `encoder_depth` is 3 and 4.
* Please refer to the attached file to see the combination of tensor shapes in each cases: [tensor_shapes.md](https://github.com/qubvel/segmentation_models.pytorch/files/8053614/tensor_shapes.md).
2. Modify the docstring for `upsampling` argument to state the condition to preserve input-output shape.
* In case (`encoder_depth`, `encoder_output_stride`) = (3, …
> Fix DeepLabV3Plus encoder depth

- segmentation_models_pytorch/decoders/segformer/decoder.py
Hi @omarequalmars,
This PR addresses a performance issue in the Segformer decoder caused by unnecessary `.contiguous()` operations. These operations significantly slowed down the training process. By removing the redundant `.contiguous()` calls, the throughput has been restored to the expected level.
I ran the following experiments and checks to replicate the anomaly under your configuration:
- Compared the implementations of Transformers and SMP, along with their throughput.
- Tested throughput using your hyperparameters.
- Tested throughput using default hyperparameters.
os: linux
gpu: v100
reference: [transformers/segformer](https://github.com/huggingface/transformers/blob/5d7739f15a6e50de416977fe2cc9cb516d67edda/src/transformers/models/segformer/modeling_segformer.py#L675)
resolve …
> Fix Segformer decoder performance

- segmentation_models_pytorch/decoders/pan/decoder.py
- segmentation_models_pytorch/decoders/pan/model.py
- tests/test_models.py
Hi @qubvel,
This PR adds support for `encoder_depth` in the PAN decoder while ensuring compatibility with previously trained models, allowing them to be loaded without any issues.
1. Added type annotations for improved code clarity and robustness.
2. Introduced support for encoder_depth with validation to handle various encoder configurations.
3. Reduced the size of tests/test_models.py while maintaining test coverage.
> Update PAN Decoder support encoder depth

- pyproject.toml
- requirements/test.txt
As of #1011, there is a new dependency on `packaging`
> Dependencies: packaging required for testing

- .github/workflows/pypi.yml
- segmentation_models_pytorch/__version__.py
contributed by @brianhou0208
Originally, SegFormer is a transformer-based semantic segmentation model known for its simplicity and efficiency. It uses a lightweight hierarchical encoder to capture multi-scale features and a minimal decoder for fast inference.
With `segmentation-models-pytorch` you can utilize the model with a native Mix Vision Transformer encoder as long as with 800+ other encoders supported by the library. Original weights are also supported and can be loaded as follows:
```python
import segmentation_models_pytorch as smp
model = smp.from_pretrained("smp-hub/segformer-b5-640x640-ade-160k")
```
See more checkpoints on the [HF Hub](https://huggingface.co/collections/smp-hub/segformer-6749eb4923dea2c355f29a1f).
Or with any other supported encoder:
```python
import …
```
> Release 0.4.0

- segmentation_models_pytorch/base/model.py
- segmentation_models_pytorch/decoders/unet/decoder.py
- segmentation_models_pytorch/decoders/unet/model.py
- tests/encoders/base.py
- tests/models/base.py
- tests/models/test_segformer.py
- tests/test_losses.py
What does this PR do?
1. Replace `scale_factor` with `size` argument in Unet `DecodeBlock` to enable forward with any image resolution (not only divisible by 32)
2. Improve Unet docstring, add example
3. Fix type hint for models (was bugged by double inheritance with HubMixin)
4. Use `inference_mode` instead of `no_grad` in tests
> Enable any resolution for Unet

- docs/conf.py
- licenses/LICENSES.md
- licenses/LICENSE_apache.md
- pyproject.toml
- requirements/minimum.old
- requirements/required.txt
- segmentation_models_pytorch/encoders/_efficientnet.py
- segmentation_models_pytorch/encoders/efficientnet.py
Supersedes #1018 
EfficientNet-PyTorch doesn't have wheels on PyPI, and is no longer maintained. Let's vendor it and maintain it ourselves. This will make SMP easier to install.
This PR doesn't deprecate the non-timm EfficientNet implementation, but we can also do that if we want to. Let's wait until we have download statistics.
Will do the same thing with pretrainedmodels once this is merged.
> Vendor efficientnet-pytorch

- docs/save_load.rst
- examples/segformer_inference_pretrained.ipynb
- segmentation_models_pytorch/base/model.py
- tests/test_base.py
Allows to load pretrained model with different number of channels
For example:
```python
import segmentation_models_pytorch as smp
model = smp.from_pretrained("smp-hub/segformer-b2-1024x1024-city-160k", classes=5, strict=False)
```
Reported in:
- https://github.com/qubvel-org/segmentation_models.pytorch/issues/1019
> Load model with mismatched sizes

- segmentation_models_pytorch/decoders/fpn/decoder.py
- segmentation_models_pytorch/decoders/fpn/model.py
- segmentation_models_pytorch/decoders/manet/decoder.py
- segmentation_models_pytorch/decoders/manet/model.py
- segmentation_models_pytorch/decoders/pan/decoder.py
- segmentation_models_pytorch/decoders/pan/model.py
- segmentation_models_pytorch/decoders/unet/model.py
- segmentation_models_pytorch/decoders/unetplusplus/decoder.py
- segmentation_models_pytorch/decoders/unetplusplus/model.py
- tests/models/test_fpn.py
- tests/models/test_manet.py
- tests/models/test_pan.py
- tests/models/test_unet.py
- tests/models/test_unetplusplus.py
> Extend usage of interpolation_mode to MAnet / UnetPlusPlus / FPN and align PAN

- segmentation_models_pytorch/__version__.py
The DPT model adapts the Vision Transformer (ViT) architecture for dense prediction tasks like semantic segmentation. It uses a ViT as a powerful backbone, processing image information with a global receptive field at each stage. The key innovation lies in its decoder, which reassembles token representations from various transformer stages into image-like feature maps at different resolutions. These are progressively combined using convolutional PSP and FPN blocks to produce full-resolution, high-detail predictions.
The model in `smp` can be used with a wide variety of transformer-based encoders
```python
import segmentation_models_pytorch as smp
model = smp.DPT("tu-mobilevitv2_175.cvnets_in1k", classes=2)
model = smp.from_pretrained("smp-hub/dpt-large-ade20k")
model = …
```
> Release v0.5.0

- segmentation_models_pytorch/losses/focal.py
Focal loss have a `reduction` parameter, but it is not set as a `self.reduction` value.
This does not affect loss functionality, but it can be misleading, because by default `__init__` function of `_Loss` sets `self.reduction` to `"mean"`.
For example:
```
>>> loss = smp.losses.FocalLoss(..., reduction="none")
>>> loss.reduction
'mean'
```
This can make checks like this fail, while they should pass
```
if hasattr(loss, "reduction") and loss.reduction != "none":
raise ValueError("basic loss must have reduction = none")
```
This is a purely cosmetical addition that should not affect anything but can improve user experience
> Explicitly set `reduction` for Focal loss

- segmentation_models_pytorch/losses/jaccard.py
All the other segmentation losses have `ignore_index` parameter, and `JaccardLoss` does not. The `ignore_index` logic was copied from Dice Loss
> Add `ignore_index` to Jaccard loss

- segmentation_models_pytorch/losses/dice.py
Fixes #1169 
Fixed two comment lines in dice.py (Line numbers 118 and 119).
> Fix minor typo in dice.py
